const registros = [
            {
                apellido: 'Marquez',
                nombre: 'Lucas',
                email: 'lucas.marquez86@gmail.com',
                genero: 'Masculino',
                contrasena: 'EntregaFinal2023',
                celular: '1160378000',
                cumpleanos: '12/10/1986',
                dni: '32654789',
            },
            {
                apellido: 'Apellido2',
                nombre: 'Nombre2',
                email: 'email2@example.com',
                genero: 'Femenino',
                contrasena: 'contrasena2',
                celular: '987654321',
                cumpleanos: '02/02/1995',
                dni: '87654321',
            },
            {
                apellido: 'Apellido3',
                nombre: 'Nombre3',
                email: 'email3@example.com',
                genero: 'Femenino',
                contrasena: 'contrasena3',
                celular: '987654321',
                cumpleanos: '21/12/1980',
                dni: '29578963',
            },
        ];